version: '2'

services:
  joomla:
    container_name: joomla
    image: joomla
    restart: always
    links:
      - mysql:mysql
    ports:
      - "8080:80"
    volumes:
      - /home/ubuntu/docker/containers/joomla:/var/www/html
    environment:
      JOOMLA_DB_HOST: mysql
      JOOMLA_DB_PASSWORD: Ausias123@@
      JOOMLA_DB_USER: root
    network_mode: "bridge"
  mysql:
    container_name: mysql
    image: mysql:5.6
    restart: always
    volumes:
      - /home/ubuntu/docker/containers/mysql:/var/lib/mysql/data
    ports:
      - "3307:3306"
    environment:
            MYSQL_ROOT_PASSWORD: Ausias123@@
    network_mode: "bridge"
  jenkins:
    container_name: jenkins
    hostname: jenkins
    image: ackstorm/debian-jenkins:2.46.2ack1
    restart: always
    volumes:
      - /srv/jenkins/jenkins_home:/var/jenkins_home
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    ports:
      - "81:8080"
    network_mode: "bridge"

